apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-rollouts
  repo: https://charts.akuity.io
  includeCRDs: true
  namespace: argo-rollouts
  version: 1.4.1-ak.0.0
  # valuesFile: values.yaml