apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: whalesay
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceAccountName: workflows
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
